changesetIgnorePatterns:
  - "**/*.{test}.{js,ts,jsx,tsx}"
  - "!(.yarn/versions/**|src/**/*|package.json|.swcrc*)"

compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.5.3.cjs
